### ISSUE TITLE
USER STORY: Filter products on indoor growing

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#12]
As a **Shopper** I want to be able to **find seeds suitable for indoor growing** so that I can **easily rule out seeds not suitable for my needs**.

# Tasks
- [x] Add indoors field on product model
- [x] Update the product view
- [x] Update the navbar with a indoors filter
- [x] Update the product html
  
# Acceptance Criteria
- A user can filter all products to find the ones suitable for indoor sowing.
