### ISSUE TITLE
USER STORY: Newsletter signup

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#14]
As a **Shopper** I want to be able to **sign up to receive newsletters from the site** so that I can **get information and discount offers in the mail**.

# Tasks
- [x] Create a newsletter app
- [x] Add the app to the setting.py file
- [x] Add a newsletter subscriber model
- [x] Set up admin.py
- [x] Add a subscribe form
- [x] Create a context.py file
- [x] Add the context file to the settings.py file
- [x] Udate the newsletter signup include html

# Acceptance Criteria
- A user can sign upp for newsletters from the site
