### ISSUE TITLE
USER STORY: View Ratings

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#15]
As a **Shopper** I want to be able to **see the the site users ratings on different products** so that I can **use that information when doing my purchases**.

# Tasks
- [x] Add a rating model to the product model.py file.
- [x] Add rating stars to the product detail view
- [x] Add rating stars to the product view.
  
# Acceptance Criteria
- A user is able to see a products rating on the product page and on its product detail page.
