### ISSUE TITLE
USER STORY: Rate Products

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#16]
As a **Shopper** I want to be able to **rate a product on the site** so that I can **show my opinion of a product, together with other users**.

# Tasks
- [x] Add a rate-product view
- [x] Add a rate url to the product url
- [x] Update the product_detail.html fille to allow a logged in user to rate the product.
- [x] Make a ls script to get a hover effect when the user is rating the product.
  
# Acceptance Criteria
- A logged in user can rate a product on the product detail page.
