### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#17]
As a **Site User** I want to be able to **easily register for an account** so that I can **have a personal account to be able to view my profile**.

# Tasks
- [x] Install crispy forms
- [x] Add crispy forms to settings.py
- [x] Install Allauth
- [x] Update settings.py for allauth
- [x] add allauth to the main url file
- [x] Update the domain name
- [x] create allauth template folder
- [x] copy allauth templates
- [x] customize signup template
  
# Acceptance Criteria
- A user can sign up to the site
