### ISSUE TITLE
USER STORY: Login/logout

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#18]
As a **Site User** I want to be able to **easily login and logout** so that I can **access my personal account**.

# Tasks
- [x] Add a link to the navbar
- [x] Add  a logout link to the navbar
- [x] Update the allauth template
  
# Acceptance Criteria
- A registered user can log in to the site
- A logged in user can log out
