### ISSUE TITLE
USER STORY: User details on profile page

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#22]
As a **logged in Site User** I want to be able to **add and change my default delivery address on my profile page** so that I can **easily make another order**.

# Tasks
- [x] Add a receiver on the model.py file
- [x] Create a profile view
- [x] Create an url
- [x] Update the project url
- [x] Create a profile form
- [x] Create a profile.html file
- [x] Update the navbar link
  
# Acceptance Criteria
- A logged in user can edit their saved default delivery address on the profile page
