### ISSUE TITLE
USER STORY: Add to basket

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#24]
As a **Shopper** I want to be able to **easily select a product to add it to the basket** so that I **don't have make annoying unnecessary clicks**.

# Tasks
- [x] create the basket app
- [x] create a basket view
- [x] create a basket.html file
- [x] create a url file
- [x] update the projects url
- [x] update the basket link on the the navbar
- [x] create a context file
- [x] add the context processor to settings.py
- [ ] ~~update the product "buy now" form ~~
- [x] update the product detail "buy now"  form
- [x] Add the total for each basket row.
- [x] Add the edit quantity functionality
- [x] Add the remove item functinality
  
# Acceptance Criteria
- An item can be added to the basket
- the content of the basket can be viewed  on the basket page
- the sum of the basket content is visible in the navbar 
- The costs are shown correctly on the basket page.
- The user can adjust the quantity of an Item.
- The user can delete an item from the bag.

**Comment by Odden69** [comment]
Closing the issue and starting a new with the open task of adding to the basket from the product page.
