### ISSUE TITLE
USER STORY: Shopping bag page

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#25]
As a **Shopper** I want to be able to **view the content of my shopping bag** so that I can **to ensure I have selected the intended products**.

# Tasks
- [x] Add a list of all items in the basket
- [x] Allow the user to adjust the quantity of  an item
- [x] Allow the user to delete an item 
- [x] Add a button to secure checkout
  
# Acceptance Criteria
- a user can see all the items in their shopping basket.
- A user can choose to go to check out and pay when they're ready.
