### ISSUE TITLE
USER STORY: Enter payment information

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#27]
As a **Shopper** I want to be able to **easily enter my payment information** so that I can **checkout easily**.

# Tasks
- [x] Create a checkout view.py file
- [x] create an url.py file
- [x] Create a template file
- [x] Update the project url.py file
- [x] Add the stripe script to the head 
- [x] Add a stripe elememts javascript file
- [x] Install Stripe
  
# Acceptance Criteria
- A user can enter payment information on the checkout page
