### ISSUE TITLE
USER STORY: Order confirmation page

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#29]
As a **Shopper** I want to be able to **view an order confirmation after checkout** so that I can **verify the content of the order**.

# Tasks
- [x] Add a checkout_success view 
- [x] Add a checkout_success url
- [x] Add a checkout_success html
  
# Acceptance Criteria
- The user is redirected to a confirmation page when the order and payment was successful.
