### ISSUE TITLE
USER STORY: Product list

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#3]
As a **Shopper** I want to be able to **view a list of all available seeds** so that I can **select the ones I like to purchase**.

# Tasks
- [x] Create the products app
- [x] Set up the category model
- [x] Set up the subcategory model
- [x] Set up the season model
- [x] Add a products view
- [x] Add an index view
- [x] Create the products.html file
- [x] Create a home url
- [x] Create a products url
- [x] Add the products url to the main url.
- [x] Update admin.py
  
# Acceptance Criteria
- All products are visible on the home url.
