### ISSUE TITLE
USER STORY: Order confirmation email

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#30]
As a **Shopper** I want to be able to **receive the order confirmation via email** so that I can **save the order confirmation**.

# Tasks
- [x] Create a confirmation email body file
- [x] Create a confirmation email subject file
- [x] Update the stripe webhook handler
  
# Acceptance Criteria
- The user receives a confirmation email when placing an order.
