### ISSUE TITLE
USER STORY: Add product

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#31]
As a **Store Owner** I want to be able to **easily add a product to my site** so that I can **sell new products**.

# Tasks
- [x]  Create a product model form. 
- [x] Create a new product view
- [x] Update the url.py file
- [x] Add a template for creating new products. 
  
# Acceptance Criteria
- A superuser can add new products to the store.
