### ISSUE TITLE
USER STORY: Edit product

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#32]
As a **Store Owner** I want to be able to **easily edit and update a product** so that I can **ensure the content is correct**.

# Tasks
- [x] Add an edit product view
- [x] Update the product url with an edit product url.
- [x] Add an edit product template
- [x] Update the product detail html with a link to edit the product.
  
# Acceptance Criteria
- A superuser can edit a product from the product detail page.
-
