### ISSUE TITLE
USER STORY: Delete Product

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#33]
As a **Store Owner** I want to be able to **easily delete a product** so that I can **make sure the site does not show products no longer for sale**.

# Tasks
- [x] Add a delete product view
- [x] Update the product url with delete product
- [x] Add a link to the product detail page to delete a product.
- [x] Add a modal to the product detail page, for user confirmation.
  
# Acceptance Criteria
- A superuser can delete a product from the database.
