### ISSUE TITLE
USER STORY: Put products up on sale

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#34]
As a **Store Owner** I want to be able to **choose to put a product up on sale** so that I can **sell out outgoing products, for instance**.

# Tasks
- [X] Add "on sale" and "discount" fields to the product model.
- [x] Add a on sale tag on the product and product detail pages.
- [x] Recalculate the shown price on the product.
- [x] Recalculate the item price in the basket with the discount.
- [x] Update the navbar with a on sale filter
  
# Acceptance Criteria
- A superuser can put a product up on sale.
- A user can see the products where a discount is avaliable.
- A user can choose to see only the products on sale by clicking the link on the navbar.
- The sum in the basket is updated with the discounts.
