### ISSUE TITLE
TO DO: Readme file

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#36]
# Tasks
- [x] Add readme.md file
- [x] Add a responsive image
- [x] Add summary
- [x] Add target audiens
- [x] Add user stories
- [x] Add wireframes.md
- [x] Add database diagram
- [x] Add SEO results
- [x] Add sitemap.xml and robots.txt
- [x] Add marketing strategies
- [x] Add existing features
- [x] Add features left to implement
- [x] Add used technologies 
- [x] Add testing results
- [x] Add deployment description
- [x] Add credits

# Acceptance Criteria
- The readme file is complete and contains all information required for PP5
