### ISSUE TITLE
TO DO: Set up Profile App

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#38]
# Tasks
- [x] Create a Profile App
- [x] Update settings.py with django default authentication
- [x] Install Django country field
- [x] Add profile model
- [x] Add auth to url.py
- [x] Update admin.py

# Acceptance Criteria
- The profile table is visible on the admin page with all the required attributes.
