### ISSUE TITLE
TO DO: Set up base template structure

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#39]
# Tasks
- [x] Create base.html
- [x] Create includes folder
- [x] Create head.html
- [x] Create header.html
- [x] Create messages.html
- [x] Create navbar.html
- [x] Create footer.html

# Acceptance Criteria
- A structure for base.html is in place
