### ISSUE TITLE
TO DO: Static and Media

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#41]
# Tasks
- [x] Create static and media folders
- [x] create base.css
- [x] create base.js
- [x] Add statics, media and templates to settings.py

# Acceptance Criteria
- Static and media folders are present in the project
