### ISSUE TITLE
TO DO: Hero Image / Message

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#43]
# Tasks
- [x] Add hero image
- [x] Update message depending on category/subcategory
- [x] Update image depending on category/subcategory (optional)

# Acceptance Criteria
- The hero image and message are visible on the product list page and updates according to category/subcategory
