### ISSUE TITLE
USER STORY: Add products to Favorites

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#49]
As a **shopper** I want to be able to **add products to my favorites** so that I can **easily go back to those products**.

# Tasks
- [x] Add favorites app
- [x] Add a favorite view to add favorites to the session
- [x] Add favorites to the products page
- [x] Add favorites to the product detail page
- [x] Add a filter to the products page to be able to view only favorites
  
# Acceptance Criteria
- A shopper can mark a product as a favorite
- A shopper can view a list of their favorite products
