### ISSUE TITLE
USER STORY: Detailed Product Page

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#5]
As a **Shopper** I want to be able to **view a detailed page of an individual product** so that I can **find out more information about requirements, sowing time etc**.

# Tasks
- [x] Create a product_detail view
- [x]  Add a product_detail template
- [x] Add an url to the product app
- [x] Add a link to the product list template
  
# Acceptance Criteria
- The product_detail view renders
- The link from an object in the product list work
