### ISSUE TITLE
USER STORY: Confirmation and Error messages

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#50]
As a **user** I want to **get an confirmation to my actions** so that I can **be sure my action has gone through**.

# Tasks
- [x] Create a message block in the base template
- [x] Create a messages html in the include folder
- [x] Create a toast include folder with toast messages
  
# Acceptance Criteria
- A triggered message is displayed to the user.
