### ISSUE TITLE
TO DO: Checkout App

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#52]
# Tasks
- [x] Create a checkout app
- [x] Create a Order and a OredLineItem model
- [x] Update the settings file with the new app
- [x] Add the app to the admin page
- [x] Create a signal.py file
- [x] Create a checkout form

# Acceptance Criteria
- The checkout app is added to the project
- The order can be handled from the admin page
- The order is updated when the shopping basket is adjusted.
