### ISSUE TITLE
USER STORY: Categories and subcategories

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#6]
As a **Shopper** I want to be able to **view different categories and subcategories of seeds** so that I can **easily find the kind I am looking for**.

# Tasks
- [x] Filter products on categories
- [x] Filter products on subcategories
- [x] Handle the herbs issue (no subcategories) 
  
# Acceptance Criteria
- All products can be viewed by filtering on categories and subcategories
