### ISSUE TITLE
USER STORY: Search bar

### ISSUE THREAD

**Issue by Odden69** [Odden69/Miller_and_Davies#8]
As a **Shopper** I want to be able to **search for a product by name, description or subcategory** so that I can **easily find the specific seed I am looking for**.

# Tasks
- [x] Add a query function to the  products view
- [x] Update the header html with the search function
- [x] Add text to clarify search result to user on the product page.
  
# Acceptance Criteria
- A user can use the search bar to filter products by a word found in name, description and subcategory.
